databases:
  - name: petstore-db
    plan: free
    databaseName: petstore
    user: petstore

services:
  - type: web
    name: petstore-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    healthCheckPath: /api/v1/pets
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petstore-db
          property: connectionString
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://petstore-frontend-a9iq.onrender.com,http://localhost:3000
      - key: SPRING_FLYWAY_SCHEMAS
        value: petapp
      - key: SPRING_HIBERNATE_DEFAULT_SCHEMA
        value: petapp

  - type: web
    name: petstore-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://petstore-backend-9wyp.onrender.com/api/v1
