spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/petstore}
    username: ${SPRING_DATASOURCE_USERNAME:petstore}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[format_sql]': true
        '[default_schema]': ${SPRING_HIBERNATE_DEFAULT_SCHEMA:petapp}
  flyway:
    schemas: ${SPRING_FLYWAY_SCHEMAS:petapp}
    baselineOnMigrate: true

server:
  port: 8080

